### ISSUE TITLE
[REFACTOR] Alert 쿼리문 리팩토링

### ISSUE THREAD

**Issue by chansik0504** [Node-study-programmers/travelevart-BackEnd#38]
## **기능 설명**
Alert 쿼리문 리팩토링, post Controller user_name 연결

## **To-Do**
- [ ] SQL문 -> QueryBuilder로 변경
- [ ] user_name 연결
- [ ] 댓글 갯수 연결
- [ ] 좋아요 수 연결
