### ISSUE TITLE
[test] 성률 예행연습

### ISSUE THREAD

**Issue by chansik0504** [Node-study-programmers/travelevart-BackEnd#6]
## **기능 설명**
폴더 생성

## **To-Do**
- [x] post 폴더 생성
- [x] comment 폴더 생성
- [x] alert 폴더 생성
